-- MySQL Script generated by MySQL Workbench
-- 10/27/15 16:35:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uniDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uniDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uniDB` DEFAULT CHARACTER SET utf8 ;
USE `uniDB` ;

-- -----------------------------------------------------
-- Table `uniDB`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uniDB`.`instructor` (
  `ID` VARCHAR(5) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `dept_name` VARCHAR(20) NULL,
  `salary` DECIMAL(8,2) NULL check (salary > 29000),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniDB`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uniDB`.`student` (
  `ID` VARCHAR(5) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `dept_name` VARCHAR(20) NULL,
  `tot_cred` DECIMAL(3,0) NULL check (tot_cred >= 0),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uniDB`.`takes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uniDB`.`takes` (
  `ID` VARCHAR(5) NOT NULL,
  `course_id` VARCHAR(8) NOT NULL,
  `sec_id` VARCHAR(8) NOT NULL,
  `semester` VARCHAR(6) NOT NULL,
  `year` DECIMAL(4,0) NOT NULL,
  `grade` VARCHAR(2) NULL,
  PRIMARY KEY (`ID`, `course_id`, `sec_id`, `semester`, `year`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
